ALTER TABLE "OtpRequest"
ADD COLUMN IF NOT EXISTS "salt" TEXT NOT NULL DEFAULT '';

ALTER TABLE "OtpRequest"
ADD COLUMN IF NOT EXISTS "userId" INTEGER NOT NULL DEFAULT 0;

ALTER TABLE "OtpRequest"
ALTER COLUMN "salt" DROP DEFAULT;

ALTER TABLE "OtpRequest"
ALTER COLUMN "userId" DROP DEFAULT;